### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 4-Leafs-Code**
I love what you have done, friend. Some of the words were misspelled and it could be a translation thing but take a look. The word developer had some letters cut off from being to long so I split it but then "I love to teach was short". What do you think? just close the Pull Request if you do not like it.

Oh and you already are a web developer so I added SR to the statement to show your still learning.

### CODE REVIEW

**Comment by Ronnie018** [comment]
I was changing it until now, take a look

**Comment by Ronnie018** [comment]
> I was changing it until now, take a look

I copied your dropdown menu

**Comment by 4-Leafs-Code** [comment]
First, it's much better I love it.

Second,... ah... friend... old buddy... old pal... how did you change the text are their more options I love it and I want it.

**Comment by 4-Leafs-Code** [comment]
But you already are a web developer please don't sell yourself short, Ronnie, because your amazing!!

**Comment by Ronnie018** [comment]
theres a page to custom that

**Comment by 4-Leafs-Code** [comment]
May I have the address please, pretty please???

**Comment by Ronnie018** [comment]
here it is https://readme-typing-svg.demolab.com/demo/

**Comment by 4-Leafs-Code** [comment]
image

Oh this is some major bull hockey!!! I need to cuddle my pillow and take a nap. I was almost asleep and I was called to the Sergeants office.

**Comment by Ronnie018** [comment]
screen

this is the screen it shows, just tell me the config u want and i get you a link

**Comment by 4-Leafs-Code** [comment]
Your the best!!!  But I'm not sure what I want for configs. I want purple, pink, or rainbow if they have it. I'll let you pick the font for me and I'll let your  graphics fib slide 😉 Thank you so much!

I'm+Clover+Baxter;I'm+4-Leafs-Code;
I'm+a+CoOwner+of+FearlessTech;
I'm+a+Jr+Fullstack+Developer;
I'm+a+Computer+Tech+Student;
I'm+a+Prisoner+in+Maine,+U.S.A.

**Pull request closed without merging**
